import Head from 'next/head'
import Script from 'next/script'

export default function PageLayout({children}){
    return (<>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        {children}
    </>)
}